const typeActions = {
    LOGIN_USER: 'LOGIN_USER',
    BUTTON_LOGIN:'BUTTON_LOGIN',
    SET_IS_FETCHING:'SET_IS_FETCHING',
    SET_IS_FETCHED:'SET_IS_FETCHED',
    ERROR_LOGIN_USER:'ERROR_LOGIN_USER',
    RESET_INITIAL_STATE:'RESET_INITIAL_STATE'
};

export default typeActions;